anvilistas/anvil-extras

client_code/Demo/__init__.py, client_code/Demo/form_template.yaml, client_code/utils.py, docs/guides/modules/utils.rst
=> Auto Refreshing Item

client_code/augment.py
close #46 
Implements a `trigger('writeback')` on all components.
It also removes the init method which was only used to create the trigger method and instead just adds `trigger` to `Component`.
It would mean that making a textbox writeback on change would be as simple as
```python
from anvil_extras import augment
def textbox_change(self, sender, **event_args):
sender.trigger('writeback')
```
=> trigger writeback

CHANGELOG.rst, client_code/utils/__init__.py, client_code/utils/_auto_refreshing.py, client_code/utils/_timed.py, client_code/utils/_writeback_waiter.py, docs/guides/modules/utils.rst
This pr does 2 things
1. Makes the util module lazy
2. includes the `wait_for_writeback` decorator
Inspired by [this post](https://anvil.works/forum/t/form-field-in-repeating-panel-not-updating-value-on-loss-of-focus-on-touch-devices/8489)
It's not just mobile
The lost focus writeback can happen after the click and then the item in the click handler is wrong!
It can be used in the following way:
```python
from anvil_extras.util import wait_for_writeback
class Form1(Form1Template):
...
@wait_for_writeback
def button_1_click(self, **event_args):
"""This method is called when the button is clicked"""
anvil.server.call('save_item', self.item)
```
---
- All anvilTemplate forms are stored in `window.anvilFormTemplates` 
- each template has a private javascript list of databindings where each …
=> Use lazy module and add a wait_for_writeback decorator

client_code/Demo/__init__.py, client_code/EditableCard/__init__.py, client_code/MessagePill/__init__.py, client_code/MultiSelectDropDown/__init__.py, client_code/PageBreak/__init__.py, client_code/ProgressBar/Determinate/__init__.py, client_code/ProgressBar/Indeterminate/__init__.py, client_code/ProgressBar/__init__.py, client_code/Quill/__init__.py, client_code/Switch/__init__.py, client_code/augment.py, client_code/messaging.py, client_code/navigation.py, client_code/popover.py, client_code/routing/__init__.py, client_code/routing/_logging.py, client_code/routing/_navigation.py, client_code/routing/_routing.py, client_code/routing/_session_expired.py, client_code/session.py, client_code/style.py, client_code/utils/__init__.py, client_code/utils/_auto_refreshing.py, client_code/utils/_component_helpers.py, client_code/utils/_timed.py, client_code/utils/_writeback_waiter.py, server_code/authorisation.py, server_code/server_utils.py
Makes for fewer potential mistakes in our file licences preamble and smaller codebase
https://spdx.dev/ids/
=> Use SPDX license identifiers

CHANGELOG.rst, client_code/ProgressBar/Determinate/__init__.py, client_code/ProgressBar/Indeterminate/__init__.py, client_code/session.py
I've removed get_uid entirely from the determinate progress bar but I can't find a clean way to replace its use for the pseudo element on the indeterminate bar.
=> Remove get_uid where possible

CHANGELOG.md, client_code/Quill/__init__.py, docs/guides/components/quill.rst
Allows toolbar to be set at runtime
stops set_html causing a focus of quill editor
=> Quill - small tweaks to implementation 

docs/guides/enterprise-installation.rst, docs/guides/index.rst
Third party dependencies are not supported in Enterprise Installations of Anvil. These docs are a fairly small change from the old Anvil Extras installation docs, detailing the clone/pull/force-push approach.
=> Add docs for enterprise installation (modified version of old installation docs)

CHANGELOG.md, client_code/storage.py, docs/guides/modules/storage.rst
This module provides a python dictionary like wrapper around `window.sessionsStorage` and `window.localStorage`
the `local_storage` object allows for persistent data across sessions.
It can be used to create a simple todo app that works offline (for example)
=> local storage wrapper

CHANGELOG.md, client_code/augment.py
Anvil added the `add_event_handler` for components so I figured we should too.
There's no point in also adding the `remove_event_handler` since it would just do the exact same thing as the anvil.Component version.
We can also pass the `original_event` as an `event_arg`. 
I was about to answer [this forum post](https://anvil.works/forum/t/on-right-click-event/9125). But realised I wanted the original event to answer it fully. 
---
nb - I called it `original_event` because jQuery does but maybe `js_event` would be a better name...?
=> augment updates

client_code/Switch/form_template.yaml
The Switch component doesn't currently support binding writeback, which is an inconvenience.
This PR adds this missing support that other components in the repo already have.
=> Allow binding writeback on the Switch component

CHANGELOG.md, client_code/Quill/__init__.py, client_code/Quill/form_template.yaml, docs/guides/components/quill.rst
close #87 
The code to implement #87 might include Quill and the imageResize module scripts in Native Libraries.
(It would need to include both since imageResize relies upon Quill existing)
Then in a form that uses a Quill component.
```python
class Form1(Form1Template):
def __init__(self, **properties):
self.init_components(**properties)
self.quill.modules = {"imageResize": {}}
```
@sebasm611 it's a bit late but how's this api for you?
=> Support quill modules

docs/guides/contributing.rst
pre commit automates all the python checks and adjusts the code.
We should add a reference to this so that it's easier to contribute.
=> Add a reference to pre-commit to the contributing guide

CHANGELOG.md, client_code/routing/__init__.py, client_code/routing/_alert.py, client_code/routing/_logging.py, client_code/routing/_routing.py
close #131 
wrapper around anvil alerts.
If an alert is dismissible then the alert will be closed on navigation
if an alert is not dismissible then navigation will be halted
---
Also included in this pr - logger doesn't save logs by default - i figure this feature is not really used and seems unnecessary to create an ever growing list of logs.
---
I'll document this as part #40 
@stenci might want to take a look at the api/code
=> include routing.alert api

CHANGELOG.md, client_code/PageBreak/__init__.py, client_code/PageBreak/form_template.yaml, docs/guides/components/page_break.rst
=> fix margin-element node and make margin_top optional

CHANGELOG.md, client_code/storage.py, docs/guides/modules/storage.rst
close #130, close #106, close #129 
I use `localforage` to wrap `localStorage` and `indexedDB`.
This pr deprecates `session_storage` - it's not particularly useful anyway.
It's deprecated because localforage doesn't have a wrapper for it.
It adds a nice api for creating a new store
This is like creating a new dictionary object.
```python
from anvi_extras.storage import indexed_db as db
todo_store = db.get_store('todos')
```
It also adds an `is_supported()` method which returns a `boolean`.
You don't get an error on import anymore.
But if you try to use the store in anyway, and it's not supported you do get 
`ExternalError: Error: No available storage method found.`
compromises and hacks:
- the repr can't expose the internals since localforage is very asyncronous and reprs can't be …
=> Use localforage to create a wrapper around indexed_db

CHANGELOG.md, client_code/PageBreak/__init__.py, client_code/PageBreak/form_template.yaml, docs/guides/components/page_break.rst
Sometimes the PDF contains horizontal grey lines, so the PageBreak lines get confused with the ones that are part of the PDF.
This new `border` property allows to change the default style to something different form the rest of the PDF. It has no effect on the generated PDF.
In one of my PDFs I'm using:
```python
self.add_component(TruckPDF(self.truck))
for crate in self.truck.crates:
self.add_component(PageBreak(border='1px dashed red'))
self.add_component(CratePDF(crate))
```
close #142
=> Add border property to PageBreak

client_code/storage.py, client_code/utils/_component_helpers.py
Another sneaky anvil update.
I've identified a couple of places in the code base where we can use it.
from the [anvil docs](https://anvil.works/docs/client/javascript/accessing-javascript#calling-asynchronous-javascript-apis):
> If you obtain a Promise object by some other route (for example, as the attribute of an object, or by constructing it directly), you can block until it resolves by calling `anvil.js.await_promise(js_promise)`. This will return the resolved value of the Promise, or raise an exception if it rejects.
=> use anvil.js.await_promise in a couple of places

CHANGELOG.md, client_code/popover.py
close #145 
This adds a feature to wait for a show/hide transition to complete - so that developers don't need to add sleeps when doing advanced things with popovers.
bootstrap provides 4 popover events `show`, `shown`, `hide`, `hidden`
race conditions occur when we've started a hide but we're in the middle of a show and haven't yet reached shown.
There isn't really a way to link the events and wait for one to complete.
So we create a javascript promise that starts when the show starts and resolves when we're shown.
This way we can wait for the transition to complete before attempting a new transition.
I've tried it on the clone for https://anvil.works/forum/t/popovers-implementing-triggering-a-popover-on-the-same-element/9799 and it works very nicely.
I add a private `_in_transition` to …
=> Popover transition

client_code/popover.py, docs/guides/modules/popover.rst
This pr does a refactor of popovers.
Features have been added and the main popover function was becoming a bit swamped.
It also closes #151:
- scroll behaviour will always hide popovers (regardless of whether `auto_dismiss` is true)
- This is because - when scrolling the page - popovers always appear on top and that can cause ghost popovers that float even though their popper component is no longer visible.
Other changes:
-  all Components can have popovers (not just Links and Buttons)
- `popover_id` is no longer a random string just the str of the next count
- `_set_transition` moved to be an attribute on the jQuery element rather than adding an attribute to the component instance.
- improved scrolling/resize behaviour that is a little cleverer.
It builds on top of #150
=> Popover refactor

client_code/Slider/__init__.py, client_code/storage.py, client_code/uuid.py
A new anvil.js feature which simplifies a couple of javascript library imports for us.
I've identified a few places where we can import modern javascript modules into python using it.
Also removed `from anvil import *` in the slider component which didn't seem to be being used at all 🤷 
(Checked all working on the demo app and ran the modules as main)
=> Use js.import_from in a few places

CHANGELOG.md, client_code/storage.py, docs/guides/modules/storage.rst
close #176 - add a serializer to fail loudly
close #102 - support serializing datetimes
fix a bug with iterating over a storage object.
`__iter__` can't suspend.
=> storage updates

CHANGELOG.md, client_code/MultiSelectDropDown/__init__.py, client_code/MultiSelectDropDown/form_template.yaml, client_code/popover.py
Some fixes to close #186 
Turns out there was a race condition in the hide event.
The exact fix comes from looking at the library code and specifically this line:
https://github.com/snapappointments/bootstrap-select/blob/6c4c75f61e69ca54d5ab557a2b90ffdccf1c63cd/js/bootstrap-select.js#L2233
The hide event/toggle version ended up being too late since the component had already been removed from the screen.
Getting the actually menu container and calling its jquery detach method works well.
I adjust the warnings so that they only get fired once.
Someone mentioned they got a bunch of warnings in a repeating panel. One is probably enough 😄 
The scroll event change was strange. But I needed that for #186 for some reason.
I also moved firing the show event for the anvil-container to the …
=> Popover multiselect

CHANGELOG.md, client_code/utils/__init__.py, client_code/utils/_canvas_helpers.py, docs/guides/modules/utils.rst
A little helper function that reduces the blurriness of canvas
based on a post I made a couple of years ago: https://anvil.works/forum/t/canvas-resolution-blurry/3765
Code from: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio#correcting_resolution_in_a_canvas
The difference
=> correct_canvas_resolution

client_code/popover.py
moves the anvil show event hack to the bootstrap `bs.inserted` event.
This is better than the `bs.shown` event since the component is in the dom but any rendering can still happen without the user noticing.
The current development branch may cause a jittery popover if something dom related happens in the show event of the popover.
=> popover: move the show event firing to the bootstrap insterted event

CHANGELOG.md, client_code/MultiSelectDropDown/__init__.py, client_code/MultiSelectDropDown/form_template.yaml
close #271 
This is because the anvil button stops the propagation of the event.
But the dropdown uses a document jQuery click event to toggle itself - which doesn't get fired!
We add a click capture event to the document, which fires before anvil's button event.
I also think that `enable_select_all` should default to False.
I didn't spot it in #255
=> Multiselect

client_code/Autocomplete/__init__.py, client_code/MultiSelectDropDown/__init__.py, client_code/MultiSelectDropDown/form_template.yaml, client_code/popover.py, client_code/utils/_component_helpers.py
This simplifies the approach for making certain components work with popovers.
The components that are problematic are those that have elements outside of the dom tree structure of the main component.
e.g. multiselect and autocomplete both have elements that don't exist as child elements
That means when they're clicked the popover would close, but it shouldn't.
The first commit uses an approach taken was to use a custom javascript event.
The second approach walks child components and raise a custom event
The second approach is probably nicer.
=> popovers: adjust approach for components that have elements outside of dom tree

client_code/Slider/__init__.py, client_code/storage.py
Reading skypack docs suggests this is better for production
smaller, faster load of javascript libraries which seems like a win.
See docs:
https://docs.skypack.dev/skypack-cdn/api-reference/pinned-urls-optimized
=> Add production urls to skypack.dev imports

docs/guides/modules/routing.rst
Minor type that nevertheless made copying and pasting the default template decorator give an error
=> Fixed typo in default_template

client_code/routing/_alert.py
support all of anvil alerts/modals that might possibly be open
This includes the stripe modal, google login modal etc
When anvil supports multiple alerts this will also just work.
=> routing - adjust alert handler

.pre-commit-config.yaml, CHANGELOG.md, client_code/routing/__init__.py, client_code/routing/_decorators.py, client_code/routing/_logging.py, client_code/routing/_router.py, client_code/routing/_utils.py, docs/guides/modules/routing.rst
@jshaffstall 
attempt number 2.
Maybe you could have a play with it by cloning this version of anvil-extras:
https://anvil.works/build#clone:6ATPRINDTZUXBKSQ=R3XKGGOVQZK6MZVHG36HCTLU
Then changing the dependency to the local copy while we still work out the kinks.
I changed a bunch of logging statements as I was working on it to make it easier to see what was going on.
The api is the one we came up with on the other branch:
```python
@routing.redirect(...) # same args as template
def redirect_no_admin():
return "login"
```
=> Template paths and redirects

client_code/MultiSelectDropDown/__init__.py, client_code/MultiSelectDropDown/form_template.yaml
close #307 
There was a race condition going on - selected was being set before items
In this PR we keep a record of the invalid selected options
We clear this list when the user interacts with the component
(+ some housekeeping)
=> Multi select

CHANGELOG.md, client_code/Demo/__init__.py, client_code/utils/__init__.py, client_code/utils/_auto_refreshing.py, docs/guides/modules/utils.rst
Just an idea which I quite like
it's potentially breaking - though I think we can get away with a minor release.
Instead of subclassing from dict - we proxy the original item object.
Changes to the proxied item will call auto_refreshing and also update the original item object.
This means that we can do `auto_refreshing` on any object.
We expect a dictionary or anvil table row, but most sensible substitutes for an `item` would work just fine.
Sending the item to the server will just send the original item.
_(I changed to `lru_cache` because `cache` is not available on the server for when the class is portable)_
referencing #89 
closes #250 
@hugetim, @rhurlbatt - you might be interested in this one since we've talked about it before
=> Auto Refreshing Proxy

client_code/utils/_auto_refreshing.py
~Before if you try to hash a dict you get `NoneType` is not callable~
~Now you still get `NoneType` is not callable 🤦~
~But - that's because of a buggy implementation in Skulpt that I'll go and fix 👍~
~In cpython this code gives `unhashable type dict`.~
Adjust the dunders of the ProxyItem to just call the builtins.
Add `__bool__`
=> Adjust dunders

.github/workflows/merge_to_main.yml
Change the name of the previous 'release' workflow to 'merge_to_main'
This pushes to the production master branch whenever the main branch is updated. No change to its content.
Add a new 'release' workflow.
This pushes to the production published branch when a new tag matching the pattern 'v*' is pushed to github.
(Also, my shiny new local yamlls lsp server reformatted some of the yaml as it didn't like the indentation).
=> Add workflow for release

CHANGELOG.md, client_code/MultiSelectDropDown/__init__.py
Fixes multi select drop down properties should be dynamic
Things like `enable_select_all`, `placeholder` and friends.
Some minor house keeping.
---
@Duncanr-glitch
Do you wanna rebase on this branch?
Let me know if you're not sure how to do that and I'll give you some incantations
=> MultiSelectDropDown: fix properties should be dynamic

CHANGELOG.md, client_code/routing/_router.py, client_code/routing/_utils.py, docs/guides/modules/routing.rst
Adjusts the implementation so that it can be a catch all, or be part of url keys with some required values
address #342
=> routing: adjust routing.ANY to be combined with required keys

CHANGELOG.md, client_code/routing/__init__.py, client_code/routing/_alert.py, docs/guides/modules/routing.rst
This PR fixes alerts 
The previous implementation relied on knowing that alerts were bootstrap alerts
This is no longer the case
Instead it provides a `routing.alert`, which wraps `anvil.alert`
The behaviour is as before, dismissible alerts with close, non-dismissible alerts will block
=> routing: fix alerts no longer block

client_code/routing/_alert.py
we don't want to use `anvil.alert` as an obvious thing to do is override `anvil.alert` with `routing.alert` which would then cause an infinite loop
=> update alert to get a stable reference to anvil.alert

CHANGELOG.md, client_code/routing/__init__.py, client_code/routing/_decorators.py, docs/guides/modules/routing.rst
tagging @steininge and @jshaffstall  who might be interested in this one following this forum post:
https://anvil.works/forum/t/lazy-loading-for-forms/18166/2
```python
@routing.lazy_route('article', url_keys=['id', routing.ANY], title="Article-{id} | RoutingExample")
def article_route():
from ..ArticleForm import ArticleForm
return ArticleForm
```
=> Lazy route

CHANGELOG.md, client_code/navigation.py, docs/guides/modules/navigation.rst
close #453
Backwards compatible
- Removes docs for `"routing"` key in favour of `set_mode`
- Removes docs for `@register(name="foo", title="Foo")` in favour of `@register("foo")` and a `"title"` key in the menu definition.
=> Navigation: set default mode and allow titles in menu definition

client_code/routing/_router.py
minor tweak
set `_force_launch` to `True` or `False`
just because of the way `routing.launch()` is called
the call can get a bit nested because a fresh template will also call `routing.launch` in its form_show event
i.e. one `routing.launch()` will start before a previous one has finished executing
=> routing: tweak to force launch global

CHANGELOG.md, docs/guides/modules/authorisation.rst, server_code/authorisation.py
=> authorisation - extract functions

client_code/utils/_component_helpers.py
this PR facilitates the possibility that the anvil designer might do some hot module reloading
we currently don't account for this in the html injector
in a scenario where all modules are reloaded, 
but the window remains the same,
injecting html in the module scope might happen multiple times
To fix that we cache injected html on `window`, rather than on the module class (which might get hot reloaded)
=> injecting html: cope with hot module reloading in the designer

CHANGELOG.md, client_code/Tabs/__init__.py, client_code/Tabs/form_template.yaml
Essentially if the Tabs change size the indicator should also move to reflect this
At the moment the indicator stays fixed which is odd
=> Tabs resize observer

CHANGELOG.md, client_code/Pivot/__init__.py
Useful if this was instantiated in the designer and self.items was None
=> Pivot: Don't completely fail if items is not set

CHANGELOG.md, client_code/Switch/__init__.py
doesn't change anything from the outside
=> Switch: make it work with undocumented designer api

CHANGELOG.md, client_code/Tabs/__init__.py, client_code/Tabs/form_template.yaml, client_code/utils/_component_helpers.py, docs/guides/components/tabs.rst
=> Tabs active bg

CHANGELOG.md, client_code/storage.py
This fixes a bug in IOS where a web worker is sleeping during an indexed db transaction
and then waking up and the transaction falls over
retrying the transaction fixes the bug
I wrote a PR direct to local forage library to fix this
They already do retries but don't retry on this particularly error type
If that gets merged we can probably remove this code and just update our version of local forage
@rhurlbatt  this is the fix for #484
=> Retry a call to the store if it fails

CHANGELOG.md, client_code/augment.py, client_code/uuid.py
augment: remove javascript hacks
instead use class monkey patching
at least this way we don't touch the javascript internals
and deprecates trigger-writeback which can now be done natively
If we think the deprecation requires a major bump then I can remove it from this PR
Maybe it's time for a major bump 🤷
=> augment: remove javascript hacks

CHANGELOG.md, client_code/Demo/form_template.yaml, client_code/Switch/__init__.py, client_code/Tabs/__init__.py, client_code/utils/_component_helpers.py, docs/guides/components/tabs.rst
@telemix probably wants to fade the active_background of a tab
So it would be better to use a hex color with an alpha value e.g. `#2196F344` where 44 is the alpha part
This PR supports that
=> improve get_rgb method to account for alpha values

client_code/Autocomplete/form_template.yaml, client_code/Chip/form_template.yaml, client_code/ChipsInput/form_template.yaml, client_code/MultiSelectDropDown/form_template.yaml, client_code/Slider/form_template.yaml, client_code/Switch/__init__.py, client_code/Tabs/form_template.yaml
The switch component wasn't incorporating the transparency correctly. As a result, the bar behind the switch was turning white when checked.
I just changed one line:
background-color: rgba(var(--color), .5);
To:
background-color: rgba(var(--color) / .5);
All the other changes (to the yaml files) were done by the Anvil Editor.
=> Fix lever color in switch component

CHANGELOG.md, client_code/persistence.py
Because:
- The server side function expects a kwarg, not a dict
Fixes #523
=> 🐛️Expand the kwargs passed by persistence get method

CHANGELOG.md, client_code/MultiSelectDropDown/__init__.py
I think this is only an issue on the current version of the self hosted app server
The app server is behind the anvil hosted runtime and so this isn't an issue generally
And this is only an issue for an app that's upgraded to use layouts
addresses #525
=> Ensure props items exists

CHANGELOG.md, client_code/storage.py
Several js objects implement the serializable interface (based on the structured clone algorithm):
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#supported_types
and that is used by indexed db.
This PR adds the Proxy class to the list of types that the storage module passes through.
=> Add Proxy class to those passed through to storage

CHANGELOG.md, client_code/non_blocking.py
Without this if the promise rejects we aren't able to catch it correctly
=> non-blocking: fix catching exceptions when directly accessing non-blocking promises

CHANGELOG.md, client_code/persistence.py, tests/test_persistence.py
The persistence module expressly prohibited changing linked class instances. It instead raised an error in the linked class descriptor. 
This PR replaces that behaviour by recording the change in the parent object's _delta.
=> Persistence data descriptor

CHANGELOG.md, client_code/augment.py
This monkey patch breaks code that does
```
self.raise_event("foo", event=some_event)
```
`event_name` should be a safe name here
you shouldn't do `raise_event("foo", event_name="bar")` because event_name gets overridden to `"foo"` anyway.
=> Fix augment name conflicts

client_code/messaging.py, docs/guides/modules/messaging.rst, tests/test_publisher.py
Added support for receiving a Logger instance as the with_logging parameter in Publisher methods and constructor.
Added support for defining the level for logging in Publisher methods (defaults to INFO).
close #569
=> Added support for Logger usage in messaging.py

CHANGELOG.md, client_code/popover.py
if the target is a node but not an element then hasAttribute is not a valid method
=> fix: nodes as targets

CHANGELOG.md, client_code/Quill/__init__.py
Raised on the forum
https://anvil.works/forum/t/anvil-extras-quill-link-fix/23710
Basically highlight and make something a link, then try to click the box to change the link url, closed the link tooltip which it shouldn't
=> Quill: fix clicking spacer should focus quill

CHANGELOG.md, client_code/Slider/__init__.py, client_code/Slider/form_template.yaml, docs/guides/components/slider.rst
Add a spacing property to the slider component
This is useful since the slider label and pip labels might overflow their container
By supporting customised spacing we no longer need to hack the overflow css of builtin anvil components
(we should remove this hack in a breaking change commit though)
This change is backwards compatible
We deprecate the spacing_above/below properties which will make them not visible in the designer
They will still be applied
but changing the spacing property will override the spacing_above/below values
=> Add spacing to slider

CHANGELOG.md, client_code/MultiSelectDropDown/DropDown/__init__.py
=> Fix zerodivision error in MultiSelectDropDown when no options are present

CHANGELOG.md, client_code/MultiSelectDropDown/__init__.py
This adopts the auto-scroll property in the multi-select dropdown suggested in this discussion item:
https://github.com/anvilistas/anvil-extras/discussions/606
=> Sets Multipicker CSS ae-ms-options ul overflow to auto

.github/workflows/check_codebase.yml, CHANGELOG.md, __init__.py, anvil.yaml, client_code/RadioGroup.py, client_code/utils/_component_helpers.py, docs/guides/components/radio_group.rst
Adds a RadioGroup component
uses some of the undocumented anvil component syntax
which I only really used because i needed the cleanup function when a RadioButton is removed
This fixes the issue:
https://anvil.works/forum/t/bug-with-radio-button-group-value-on-forms-not-in-page/11404
you just need to to add a RadioGroup to your existing form
`self.rg = RadioGroup(buttons=[self.radio_button_1])`
but it also can be used as container in the designer
or dropdown like approach where you just set the `.items` property
=> feat: RadioGroup

CHANGELOG.md, client_code/Autocomplete/__init__.py, client_code/Autocomplete/form_template.yaml
Considerations: this is not documented api
Since m3 overrides the pluggable_ui["anvil.TextBox"]
It means that anyone using an autocomplete component in an m3 app will get an m3 textbox instead of an anvil textbox,
which is probably what they want, but might be unexpected
especially if they've added some css
Might be considered breaking, but I think it's probably an enhancement??
Also adds virtualization, since we added it for the other list rendering component, why not
addresses discussion #603
=> implement autocomplete with pluggable_ui textbox

CHANGELOG.md, client_code/utils/_view_transition.py
not sure this is the right fix, but wrapping it in a try except might work
trying to avoid the random error about invalid state
see:
https://anvil.works/forum/t/anyone-seen-invalidstateerror-view-transition-was-skipped-because-document-visibility-state-is-hidden-with-anvil-router/24990/6
=> Fix: wrap view transition in try except to mitigate against random errors

CHANGELOG.md, client_code/MultiSelectDropDown/DropDown/__init__.py
a quick fix for preventing the search filter box from losing focus immediately after it receives focus
fixes #626
=> Fix: chrome tablet focus issue
