anvilistas/anvil-extras

- README.rst
- docs/guides/contributing.rst
- docs/guides/index.rst
- docs/guides/installation.rst
- docs/guides/popover.rst
- docs/index.rst
Preview available at https://anvil-extras.readthedocs.io/en/docs/
> Add installation and contribution docs

- client_code/routing/__init__.py
- client_code/routing/_logging.py
- client_code/routing/_navigation.py
- client_code/routing/_routing.py
- client_code/routing/_session_expired.py
> include the routing module

- .pre-commit-config.yaml
- README.rst
- client_code/ProgressBar/Indeterminate/__init__.py
- client_code/popover.py
- client_code/routing/_routing.py
- docs/guides/modules/augmentation.rst
- docs/guides/modules/authorisation.rst
- docs/guides/modules/index.rst
- docs/guides/modules/navigation.rst
- docs/guides/modules/popover.rst
- requirements.txt
- server_code/server_utils.py
add a pre commit hook and resulting changes
https://pre-commit.com/#pre-commit-configyaml---hooks
> pre commit hook

- client_code/PageBreak/__init__.py
- client_code/PageBreak/form_template.yaml
> Add margin_top property to PageBreak

- docs/guides/installation.rst
- docs/guides/modules/authorisation.rst
> Upgrade instructions

- CHANGELOG.rst
- client_code/augment.py
- docs/guides/modules/augmentation.rst
> add a pagination click event to datagrids

- CHANGELOG.rst
- client_code/Demo/form_template.yaml
- client_code/Switch/__init__.py
- client_code/Switch/form_template.yaml
changes the css to use the materialize version
it doesn't change size in the same way as the other one - but that's fine I think.
I've added pre and post text.
colors dynamic in the same way
> Switch with materialize css

- client_code/Demo/__init__.py
- client_code/Demo/form_template.yaml
- client_code/Slider/__init__.py
I upped the anti in the demo and made some improvements as I did so.
> Improve custom formatter for slider and make demo a little more involved

- docs/guides/components/autocomplete.rst
presssed_enter -> pressed_enter
> autocomplete.rst typo

- CHANGELOG.md
- client_code/messaging.py
Currently, unsubscribe method does not unsubscribe.
> Fix messaging.py unsubscribe bug

- client_code/Demo/__init__.py
- docs/guides/modules/utils.rst
> Document auto-refresh reference-breaking behavior and revise related Demo code

- CHANGELOG.md
- client_code/navigation.py
- docs/guides/modules/navigation.rst
> Add navigation.emulate_link_click

- CHANGELOG.md
- client_code/Autocomplete/__init__.py
- client_code/Tabs/__init__.py
close #103 
and a small tweak to the transition for tabs highlight color 😬
> Small fixes

- client_code/storage.py
Add ", " between multiple items
> Improve Storage repr

- CHANGELOG.md
- client_code/popover.py
- docs/guides/modules/popover.rst
close #120 and close #119.
Note i changed the f-string since the [parallel dependency](https://github.com/s-cork/Popover) still supports python2.
> Popover updates

- CHANGELOG.md
- client_code/storage.py
oops - i documented clear and update but forgot to add them 🤦 
close #124
> Storage missing

- docs/guides/contributing.rst
> Remove outdated contributing guideline

- client_code/routing/_routing.py
- docs/guides/enterprise-installation.rst
- docs/guides/installation.rst
- docs/guides/modules/utils.rst
This will show a helpful error message instead of just
interrupting the page load with a generic error message.
> Manage error during title formatting

- CHANGELOG.md
- client_code/MultiSelectDropDown/__init__.py
- client_code/MultiSelectDropDown/form_template.yaml
> Hide MultiSelect drop menu when component hidden

- CHANGELOG.md
- client_code/popover.py
close #148 
A sort of hack here but it works pretty well
> popover: allow component's show and hide events to trigger

- docs/guides/components/multi_select_dropdown.rst
- docs/guides/modules/popover.rst
> Multi select items

- CHANGELOG.md
- client_code/Autocomplete/form_template.yaml
> Add missing props to the designer for Autocomplete

- js/designer_components/DesignerComponent.ts
- js/designer_components/README.md
some internal docs both as a reminder for me about what I was trying to do.
And for others brave enough to try.
> Some initial guidance for creating designer components

- js/designer_components/DesignerComponent.ts
Some doc strings for `static defaults` updated after I remembered what they were for.
Support the `defaults` static attribute for `setProp` as well as `update`.
> DesignerComponent: remembered what defaults were for!

- client_code/Pivot/__init__.py
Final commit on the pivot failed to push for some reason - this fixes a cut and paste error that stops the thing working.
> Fix code order

- js/designer_components/README.md
I want to sound appropriately discouraging.
Sort of - "yes it is magic" - "don't try this at home" - vibes
> more updates to designer components readme

- client_code/animation.py
This is live so no need for our own implementation.
> anvil.js.get_dom_node now supports dom_nodes

- docs/guides/components/multi_select_dropdown.rst
Edited to make the items section to make it a little easier to read with additional text lines.
close #205
> MultiSelectDropDown documentation formatting

- .github/ISSUE_TEMPLATE/custom.md
- docs/guides/components/multi_select_dropdown.rst
> fix white space

- client_code/routing/_routing.py
'triggerd' corrected to 'triggered'
close #211
> Corrected typo in print statement in routing.py

- .github/workflows/check_codebase.yml
- server_code/lazy_module_loader.py
- server_code/serialisation.py
> add a lazy module loader and load marshmallow using it

- client_code/routing/_routing.py
remove the page from cache before checking to see if we can get by with doing nothing.   This addresses the issue described in https://github.com/anvilistas/anvil-extras/issues/243
Note that I do not have a testing environment setup to test this! 
Close #243
> If load_from_cache is false

- CHANGELOG.md
- client_code/augment.py
because @advancedhealthsys asked
https://anvil.works/forum/t/augment-remove-event-handler/11267
> Augment: Remove event handler

- client_code/PageBreak/form_template.yaml
> PageBreak: Keep border thickness in print mode

- CHANGELOG.md
- client_code/popover.py
- docs/guides/modules/popover.rst
> popvers: Support adjusting changing the container and scroll behaviour

- client_code/popover.py
- docs/guides/modules/popover.rst
> popover: bugfix - selector breaks non manual triggers

- client_code/routing/_routing.py
- docs/guides/modules/routing.rst
I've made a start in moving over the documentation.
> Routing docs

- CHANGELOG.md
- client_code/utils/__init__.py
- docs/guides/modules/utils.rst
I also reorganised the `__dir__` to be alphabetical
> implement utils.import_lib and use this for our own lazy utils loader

- .pre-commit-config.yaml
- CHANGELOG.md
- client_code/MultiSelectDropDown/__init__.py
- client_code/MultiSelectDropDown/form_template.yaml
- docs/guides/components/multi_select_dropdown.rst
> MultiSelect

- client_code/MultiSelectDropDown/__init__.py
address #307 
This was a bit of a nightmare
The docs say that user events are distinguished in a certain way
but they are not distinguished by the selectAll button clicks!
So we hack our way into signalling whether a selectAll was triggered by a user or not
steps taken:
- **HACK 1:** we add a click handler to the selectAll/deselectAll buttons that turns on the flag `_select_all_is_user`
- the selectAll button is clicked
- the changeAll function is called
- this raises the change event
- **Hack 2:** the changeAll function is wrapped so that it turns off the flag `_select_all_is_user`
- we do this because the changeAll only triggers the change event if something has changed
- in the change event we also turn off the flag to avoid any writeback infinite loops
> support selectAll triggers writeback

- CHANGELOG.md
- client_code/augment.py
documented here:
https://learn.jquery.com/events/event-extensions/
> Augment - mitigate against jquery changing the event type

- CHANGELOG.md
- client_code/popover.py
> popovers: maybe fix scrolling on mobile where target is the document

- CHANGELOG.md
- client_code/augment.py
the data grid one is a 🤦  moment.
> augment: fixes

- client_code/Slider/form_template.yaml
the material design adds a 1px bottom margin which is very annoying.
> Fix annoying margin on slider

- client_code/hashlib.py
> hashlib - don't use a keyword argument in partial 

- server_code/serialisation.py
> Added conditional to check if table_name was in ignore_column keys

- CHANGELOG.md
- client_code/routing/__init__.py
- client_code/routing/_router.py
- client_code/routing/_utils.py
- docs/guides/modules/routing.rst
> routing: add catch all for query params, routing.ANY

- client_code/Autocomplete/__init__.py
> autocomplete: check the keydown event has a key attribute :shrug:

- CHANGELOG.md
- server_code/serialisation.py
- tests/test_serialiser.py
> Serialisation: fix accelerated linked columns go missing

- CHANGELOG.md
- client_code/routing/__init__.py
fix be safe and remove any matching url from the cache across all templates not just the current one
close #367
> Routing cache

- CHANGELOG.md
- client_code/MultiSelectDropDown/__init__.py
> multiselect - fix events stop firing after the multiselect is destroyed

- CHANGELOG.md
- client_code/routing/__init__.py
- client_code/routing/_router.py
> Routing - update form.url_dict

- client_code/Autocomplete/__init__.py
Fixes anvilistas/anvil-extras#377
> Fix NotFoundError in Autocomplete()._on_hide

- CHANGELOG.md
- client_code/storage.py
- client_code/uuid.py
This will allow a service to import these scripts in advance 👍
> Check the window before dynamically importing scripts

- CHANGELOG.md
- client_code/Autocomplete/form_template.yaml
- client_code/Chip/form_template.yaml
- client_code/ChipsInput/form_template.yaml
- client_code/MultiSelectDropDown/form_template.yaml
- client_code/Quill/form_template.yaml
- client_code/Slider/form_template.yaml
- client_code/Switch/form_template.yaml
- client_code/Tabs/form_template.yaml
recent feature added to anvil allows custom components to define enum properties.
> Enum properties

- CHANGELOG.md
- client_code/routing/_utils.py
🤦 
a version bump for this would be appreciated 👍
> Fix [routing.ANY] throws TypeError

- client_code/MultiSelectDropDown/__init__.py
support native library injection of bootstrap multiselect
If it exists we don't need to inject the js/css
tagging @rhurlbatt 
see discussion #390
> Multi select - support preloading js/css

- CHANGELOG.md
- client_code/storage.py
> storage: fix serialising dict values

- .pre-commit-config.yaml
- CHANGELOG.md
- client_code/Autocomplete/__init__.py
- client_code/MultiSelectDropDown/__init__.py
- client_code/MultiSelectDropDown/form_template.yaml
- client_code/Quill/__init__.py
- client_code/animation.py
- client_code/utils/_deprecated.py
- docs/guides/components/multi_select_dropdown.rst
> multi-select-dropdown: add format_selected_text override

- CHANGELOG.md
- client_code/zod/__init__.py
- client_code/zod/_types.py
- client_code/zod/_zod_error.py
- client_code/zod/errors.py
- client_code/zod/helpers/__init__.py
- client_code/zod/helpers/dict_util.py
- client_code/zod/helpers/error_util.py
- client_code/zod/helpers/parse_util.py
- client_code/zod/helpers/regex.py
- client_code/zod/helpers/util.py
- client_code/zod/locales/__init__.py
- client_code/zod/locales/en.py
- docs/guides/modules/zod.rst
- tests/test_persistence.py
- tests/test_zod.py
Assuming we think it’s ready. 
You might want to try it on a personal project first.
> zod: add zod to anvil-extras

- client_code/persistence.py
- docs/guides/modules/persistence.rst
- Update imports from `anvil_labs` to `anvil_extras`
- Record any initial `kwargs` passed to a `PersistedClass` in `self._delta` so that any calls to `add()` correctly pass them onto the server.
Closes #407
> persistence: Fix the add book example in the docs

- CHANGELOG.md
- client_code/non_blocking.py
- docs/guides/modules/non_blocking.rst
second commit is the changes from the version in anvil-labs
> Non blocking

- CHANGELOG.md
- client_code/Autocomplete/__init__.py
> autocomplete: fix suggestion offset position in m3 theme

- client_code/Autocomplete/__init__.py
> fix removing suggestions

- CHANGELOG.md
- client_code/Autocomplete/__init__.py
addresses this issue:
https://anvil.works/forum/t/autocomplete-not-populating-immediately/17589
> Autocomplete: allow changing the suggestions to force the UI to change

- CHANGELOG.md
- client_code/utils/_writeback_waiter.py
> wait_for_writeback: pure python implementation

- CHANGELOG.md
- client_code/Autocomplete/__init__.py
- client_code/Autocomplete/form_template.yaml
- docs/guides/components/autocomplete.rst
> Autocompletion: Add a filter mode option

- client_code/animation.py
- docs/guides/modules/animation.rst
> Animate - fix up docs and messages

- docs/guides/modules/popover.rst
> popover - note on disabled components

- client_code/routing/_router.py
This allows `routing.launch()` to be called from a landing/login page
where the landing/login page is not a routing template.
see this thread for context:
https://anvil.works/forum/t/anvil-extras-hash-routing-cant-make-it-navigate/18599/2
> routing: force launch

- CHANGELOG.md
- client_code/navigation.py
- docs/guides/modules/navigation.rst
close #383
naming suggestions welcome
> navigation - support a condition

- client_code/Switch/__init__.py
minor change
doesn't really have any effect right now
But it might if/when you can double click to edit the text of a Checkbox component in the new designer
> Switch: improve designer api support

- CHANGELOG.md
- client_code/routing/_router.py
> Fix: routing properties are lost when changing template

- client_code/Switch/__init__.py
Walk the firstElement child rather than query selector
Switch: remove unused api
> Switch: Minor changes

- CHANGELOG.md
- client_code/routing/_router.py
> routing: fix check stale

- CHANGELOG.md
- client_code/logging.py
> logging - add missing date argument, close #502

- CHANGELOG.md
- client_code/logging.py
> logging: fix critical error message

- CHANGELOG.md
- client_code/non_blocking.py
- docs/guides/modules/non_blocking.rst
add a property to get the a raw javascript promise
> non-blocking: add promise getter

- CHANGELOG.md
- client_code/MultiSelectDropDown/__init__.py
> multiselect: fix visible property

- CHANGELOG.md
- client_code/MultiSelectDropDown/__init__.py
> MutliSelect - loses state when toggling properties

- CHANGELOG.md
> Added changelog item for #517

- CHANGELOG.md
- client_code/routing/_navigation.py
> routing - fix history state might be the wrong shape

- CHANGELOG.md
- client_code/routing/_router.py
fixes a bug where on_form_load is called with a stale form
> routing - fix stale form load

- CHANGELOG.md
- client_code/routing/_router.py
- client_code/zod/helpers/dict_util.py
I think the original logic was just wrong
Think I missed the case with redirects have condition None
> routing: fix redirect logic

- CHANGELOG.md
- client_code/persistence.py
> Fix handling of missing rows for Linked Attributes

- CHANGELOG.md
- client_code/Slider/__init__.py
> Slider: support dynamic connect property

- CHANGELOG.md
- client_code/MultiSelectDropDown/__init__.py
- client_code/MultiSelectDropDown/form_template.yaml
> Fix: hide dropdown when form is hidden

- CHANGELOG.md
- client_code/MultiSelectDropDown/__init__.py
> Fix Multiselect width when using "fit" causes select-all buttons to overlap

- CHANGELOG.md
- client_code/MultiSelectDropDown/__init__.py
> Fix multi select regression

- CHANGELOG.md
- client_code/popover.py
> fix popovers on forms with layouts

- client_code/persistence.py
From comparing stores to comparing keys because it stopped dropdowns working properly in the demo app
> Change the eq method in persistence

- CHANGELOG.md
- client_code/persistence.py
- tests/test_persistence.py
@uglyfruitcake this should fix the dropdown problems you hit this week
> Fix linked class attributes having no linked row

- client_code/persistence.py
The change log already has an entry that covers this
> Fix persistence bug for when linked class has no store

- CHANGELOG.md
- client_code/Autocomplete/__init__.py
fixes https://github.com/anvilistas/anvil-extras/discussions/595
> fix autocomplete enter

- .github/workflows/check_codebase.yml
- CHANGELOG.md
- client_code/utils/_component_helpers.py
This PR allows theme colors to be dynamic
E.g. if you set the tab background color to theme:Primary
then when you change `theme_colors["Primary"]` the tab background will just change as expected
By using a TextBox as a dummy node, we let anvil tell us what color is being used under the hood
If it's a theme color then we get a `var(--primary-obsucre-reference-v942)` 
Which we can now use 🪄
> Better get color

- CHANGELOG.md
- client_code/MultiSelectDropDown/DropDown/__init__.py
- client_code/MultiSelectDropDown/DropDown/form_template.yaml
- client_code/MultiSelectDropDown/__init__.py
- client_code/virtualize.py
feat: implement virtual scrolling for dropdown options to improve performance with large lists
update change log
> feat: implement virtual scrolling for dropdown options to improve performance with large lists

- CHANGELOG.md
- client_code/Autocomplete/__init__.py
use name mangling to fix issue with autocompletion name conflicts
> Fix: autocomplete name conflicts in m3
